on: [push]
name: Docker Action PoC

jobs:
  hello_world_from_Docker:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        id: hello
        # uses: GH-foundations-markdown/docker-action-test@v1
        uses: ./docker-action-test@v1
        with:
          who-to-greet: 'Eficodean'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
